language: c
compiler:
  - gcc
  - clang
env:
  - MRUBY_VERSION=1.2.0
  - MRUBY_VERSION=master
matrix:
  allow_failures:
    - env: MRUBY_VERSION=master
branches:
  only:
    - master
before_install:
    - sudo apt-get -qq update
install:
    - sudo apt-get -qq install rake bison git gperf cgroup-lite libcap-dev libargtable2-dev
script:
  - rake test
