dist: trusty
sudo: required

language: c
# before_install:
addons:
  apt:
    packages:
      - util-linux
      - rake
      - psmisc
      - bison
      - git
      - gperf
      - cgroup-lite
      - libpam0g-dev
      - autotools-dev
      - libcap-dev
      - libargtable2-dev
      - parallel
compiler:
  - gcc
  - clang
env:
  - MRUBY_VERSION=""
  # - MRUBY_VERSION=master
branches:
  only:
    - master
cache:
  directories:
    - mruby

before_script:
  # clang path was not found when using sudo
  - sudo sed -e "s?/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin?${PATH}:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin?g" --in-place /etc/sudoers
script:
  - rake consistent
  - rake compile
  - sudo /usr/bin/rake test:bintest
  - sudo /usr/bin/rake test:mtest

notifications:
  slack:
    secure: KAjlH+WzxWhsJfByqXWVxyC1c685uAmCVPxg1h0CDG7jTYs5FV1PI/WhtNg61QEDf3VZSXcQd1hgRILSIay+Sz9z346o/3oJs6WzqI7BTqN0nJ1zPJ4HDLk5dk0YG5mDrq3K/OFtCrEUxGu9vIp7zd6tLAah4wYQ3H5ehNoTaF6gPseBYWpDApNHIVC2TtpzZfqtaY2Q/J9WHPtccobLxH72pujRfxNIt8vldOKU0oT4Q7QeZr3zvCUcyCXj6ewBIEMcy3hfLlgjbVxKW+BjDbbpSQK7CgATu+jkvc1wxUfDHyt1ezaltvfWLv7yk3ru7cw28Klb3szj8pfgaGDLu+SlhhrFra4veqyNeY7youN63MzzgjMONnRZeYBdWHkIUkJ/nU50dKiwF02flMAd1/aJCM5VMUd8ljBpW6QR5amf4bZlyzsBLrWjdDNNpAjTvShkVVHhpGqZ7doSI3WeRORYfPTxwdOnTvhIDnaqoKYVKs4Lzx/Av+Q9qglMc98NIVN5iqc2dpdtUVnyMEEZxoldwU9w8rbj/L/tHys7nmNm4dR7xpdtvWjv6YsIeuYVUMCq971bMV6aPLSwkMMTXQg3VW3J5ZhSRX2wtgZq3aMGpne0x92cUlPSWFi30wt7LxSAO1fY+K90/mCe7X7oItvcjx8vu3uXANac3T0gbcc=
